apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: nginx
          image: ghcr.io/dark-charismsa/artifact-pipeline@sha256:11d69ed05416858921c261b3c025ef645c286b59d9e6a6d437978d0c8c8a6e23
          ports:
            - containerPort: 80
