apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: nginx
          image: ghcr.io/dark-charismsa/artifact-pipeline@sha256:a2a6728aa72337fbfe1a891e23cdcb353583c234a32747856f4972cbc829cc44
          ports:
            - containerPort: 80
